/*
 * Copyright 2018 - Michael Powers
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifdef USE_PGSQL
#include <postgresql/libpq-fe.h>
#include "weather.h"

/**
 * The PostgreSQL connection string to use.
 */
#define PGSQL_CONNECT_STRING "host=192.168.1.100 dbname=weather user=weather password=password"
/**
 * The query to use to insert a new sample.
 */
#define PGSQL_QUERY "INSERT INTO weather (record_start, record_end, record_temp, record_wind_speed, record_wind_spins, record_rain_depth, record_rain_tips) VALUES ($1, $2, $3, $4, $5, $6, $7)"

/**
 * This function records samples from the weather station to a PostgreSQL
 * database.
 * @param startStr The sample start time in YYYY-MM-DD HH:MM:SS format.
 * @param endStr The sample end time in YYYY-MM-DD HH:MM:SS format.
 * @param temp The temperature to record.
 * @param wind The wind speed to record.
 * @param spins The number of ticks generated by the wind sensor.
 * @param rain The rain depth to record.
 * @param tips The number of tips of the rain meter.
 */
void record_samples_to_pgsql(char* startStr, char* endStr, float temp, float wind, int spins, float rain, int tips) {
	char tempStr[50], windStr[50], windSpinsStr[50], rainStr[50], rainTipsStr[50];
	const char * const params[] = { startStr, endStr, tempStr, windStr, windSpinsStr, rainStr, rainTipsStr };
	sprintf((char*)&tempStr, "%f", temp);
	sprintf((char*)&windStr, "%f", wind);
	sprintf((char*)&windSpinsStr, "%i", spins);
	sprintf((char*)&rainStr, "%f", rain);
	sprintf((char*)&rainTipsStr, "%i", tips);

	PGconn* con = PQconnectdb(PGSQL_CONNECT_STRING);
	if(PQstatus(con) != CONNECTION_OK) {
		printf("Problem connecting to database: %s\n", PQerrorMessage(con));
		PQfinish(con);
		return;
	}

	PGresult* result = PQexecParams(con, PGSQL_QUERY, 7, NULL, params, NULL, NULL, 0);
	if(PQresultStatus(result) != PGRES_COMMAND_OK) {
		printf("Problem executing query: %s\n", PQerrorMessage(con));
	}
	PQclear(result);
	PQfinish(con);
}

/**
 * Register ourselves with the plugin system.
 */
RECORDER_INIT(PGSQL) {
    add_recorder("pgsql", &record_samples_to_pgsql);
}
#endif